version: 1
models:
  local-gguf:
    backend: llamacpp
    local_path: /replace/with/model.gguf
    inference:
      context_size: 4096
      temperature: 0.0
  hf-model:
    backend: transformers
    hf_id: organization/model-name
    inference:
      dtype: bfloat16
      temperature: 0.0
  vllm-model:
    backend: vllm
    hf_id: organization/model-name
    inference:
      dtype: bfloat16
      temperature: 0.0